name: Send telegram message
description: Send message to telegram (JavaScript code)

inputs:
  chat:
    description: Telegram chat ID
    required: true
  token:
    description: Telegram API token
    required: true
  result:
    description: Result (success, failure, skipped, cancelled)
    required: true
    default: success

runs:
  using: node16
  main: dist/index.js
